import fs from 'node:fs';
import PDFDocument from 'pdfkit';
import expenseRepository from '../repositories/expense.repository.js';
import expenseService from './expense.service.js';
import { BRAND } from '../constants/branding.js';
import { roleHasPermission } from '../security/rbac.js';
import { PERMISSIONS } from '../constants/permissions.js';
import { currentMonthParam, parseMonthParam } from '../utils/dateRange.js';
import mongoose from 'mongoose';

const BATCH_SIZE = 500;
const ROW_HEIGHT = 14;
const PAGE_MARGIN = 40;
const FOOTER_ZONE = 34;
const TABLE_HEADER_HEIGHT = 20;

const formatPkr = (amount) =>
  new Intl.NumberFormat('en-PK', { style: 'currency', currency: 'PKR', maximumFractionDigits: 0 }).format(
    amount ?? 0,
  );

const formatDate = (value) =>
  value
    ? new Intl.DateTimeFormat('en-PK', { dateStyle: 'medium', timeZone: 'UTC' }).format(new Date(value))
    : '—';

const formatDateTime = (value) =>
  new Intl.DateTimeFormat('en-PK', {
    dateStyle: 'medium',
    timeStyle: 'short',
    timeZone: 'Asia/Karachi',
  }).format(new Date(value));

const paymentLabel = (method) =>
  ({ cash: 'Cash', card: 'Card', bank: 'Bank', mobile_wallet: 'Wallet', other: 'Other' }[method] ?? method);

class ExpenseReportService {
  buildExportFilter(query, reqUser, roles) {
    const month = query.month ?? currentMonthParam();
    const range = parseMonthParam(month);
    const canReadAll = roleHasPermission(roles, PERMISSIONS.EXPENSE_READ_ALL);

    const filter = {
      date: { $gte: range.start, $lte: range.end },
    };

    if (!canReadAll) {
      filter.userId = new mongoose.Types.ObjectId(reqUser.id);
    } else if (query.userId) {
      filter.userId = new mongoose.Types.ObjectId(query.userId);
    }

    if (query.categoryId) filter.categoryId = new mongoose.Types.ObjectId(query.categoryId);

    return { filter, month, range, canReadAll };
  }

  contentBottom(doc) {
    return doc.page.height - PAGE_MARGIN - FOOTER_ZONE;
  }

  pageWidth(doc) {
    return doc.page.width - PAGE_MARGIN * 2;
  }

  /** Draw single-line text at fixed position without triggering auto page breaks. */
  safeText(doc, text, x, y, options = {}) {
    doc.text(String(text ?? ''), x, y, {
      lineBreak: false,
      ellipsis: true,
      ...options,
    });
    doc.x = PAGE_MARGIN;
    doc.y = y;
  }

  drawLogo(doc, x, y, maxWidth = 60, maxHeight = 60) {
    if (!fs.existsSync(BRAND.logoPath)) return;
    doc.image(BRAND.logoPath, x, y, { fit: [maxWidth, maxHeight] });
    doc.x = PAGE_MARGIN;
    doc.y = y;
  }

  drawPageFooter(doc, meta, pageNum) {
    const w = this.pageWidth(doc);
    const y1 = doc.page.height - PAGE_MARGIN - 22;
    const y2 = doc.page.height - PAGE_MARGIN - 12;

    doc.fontSize(7.5).fillColor('#8E8E93').font('Helvetica');
    this.safeText(
      doc,
      `${BRAND.name} · Confidential expense report · Page ${pageNum}`,
      PAGE_MARGIN,
      y1,
      { width: w, align: 'center' },
    );
    this.safeText(
      doc,
      `Generated by ${meta.generatedBy} on ${meta.generatedAt}`,
      PAGE_MARGIN,
      y2,
      { width: w, align: 'center' },
    );
    doc.font('Helvetica');
  }

  drawTableHeader(doc, y, canReadAll) {
    const w = this.pageWidth(doc);
    doc.save();
    doc.rect(PAGE_MARGIN, y, w, TABLE_HEADER_HEIGHT - 2).fill('#F2F2F7');
    doc.restore();

    doc.fontSize(7.5).fillColor('#3C3C43').font('Helvetica-Bold');

    if (canReadAll) {
      this.safeText(doc, 'Date', PAGE_MARGIN + 4, y + 5, { width: 66 });
      this.safeText(doc, 'Title', PAGE_MARGIN + 74, y + 5, { width: 118 });
      this.safeText(doc, 'Category', PAGE_MARGIN + 196, y + 5, { width: 78 });
      this.safeText(doc, 'Pay', PAGE_MARGIN + 278, y + 5, { width: 48 });
      this.safeText(doc, 'Employee', PAGE_MARGIN + 330, y + 5, { width: 88 });
      this.safeText(doc, 'Amount', PAGE_MARGIN + 422, y + 5, { width: 90, align: 'right' });
    } else {
      this.safeText(doc, 'Date', PAGE_MARGIN + 4, y + 5, { width: 72 });
      this.safeText(doc, 'Title', PAGE_MARGIN + 80, y + 5, { width: 148 });
      this.safeText(doc, 'Category', PAGE_MARGIN + 232, y + 5, { width: 92 });
      this.safeText(doc, 'Pay', PAGE_MARGIN + 328, y + 5, { width: 58 });
      this.safeText(doc, 'Amount', PAGE_MARGIN + 390, y + 5, { width: 122, align: 'right' });
    }

    doc.font('Helvetica');
    doc.x = PAGE_MARGIN;
    doc.y = y + TABLE_HEADER_HEIGHT;
    return y + TABLE_HEADER_HEIGHT;
  }

  drawTableRow(doc, expense, y, rowIndex, canReadAll) {
    const w = this.pageWidth(doc);

    if (rowIndex % 2 === 1) {
      doc.save();
      doc.rect(PAGE_MARGIN, y, w, ROW_HEIGHT).fill('#FAFAFA');
      doc.restore();
    }

    doc.fontSize(7).fillColor('#1C1C1E').font('Helvetica');
    const category = expense.categoryId?.name ?? expense.category?.name ?? '—';
    const employee = expense.userId?.firstName
      ? `${expense.userId.firstName} ${expense.userId.lastName ?? ''}`.trim()
      : expense.user?.fullName ?? '—';

    if (canReadAll) {
      this.safeText(doc, formatDate(expense.date), PAGE_MARGIN + 4, y + 3, { width: 66 });
      this.safeText(doc, expense.title ?? '—', PAGE_MARGIN + 74, y + 3, { width: 118 });
      this.safeText(doc, category, PAGE_MARGIN + 196, y + 3, { width: 78 });
      this.safeText(doc, paymentLabel(expense.paymentMethod), PAGE_MARGIN + 278, y + 3, { width: 48 });
      this.safeText(doc, employee, PAGE_MARGIN + 330, y + 3, { width: 88 });
      this.safeText(doc, formatPkr(expense.amount), PAGE_MARGIN + 422, y + 3, { width: 90, align: 'right' });
    } else {
      this.safeText(doc, formatDate(expense.date), PAGE_MARGIN + 4, y + 3, { width: 72 });
      this.safeText(doc, expense.title ?? '—', PAGE_MARGIN + 80, y + 3, { width: 148 });
      this.safeText(doc, category, PAGE_MARGIN + 232, y + 3, { width: 92 });
      this.safeText(doc, paymentLabel(expense.paymentMethod), PAGE_MARGIN + 328, y + 3, { width: 58 });
      this.safeText(doc, formatPkr(expense.amount), PAGE_MARGIN + 390, y + 3, { width: 122, align: 'right' });
    }

    doc.font('Helvetica');
    doc.x = PAGE_MARGIN;
    doc.y = y + ROW_HEIGHT;
    return y + ROW_HEIGHT;
  }

  startNewPage(doc, meta, pageNumRef, { withTableHeader = false, canReadAll = false, sectionTitle } = {}) {
    this.drawPageFooter(doc, meta, pageNumRef.value);
    doc.addPage();
    pageNumRef.value += 1;

    let y = PAGE_MARGIN;
    if (sectionTitle) {
      doc.fontSize(11).fillColor('#1C1C1E').font('Helvetica-Bold');
      this.safeText(doc, sectionTitle, PAGE_MARGIN, y, { width: this.pageWidth(doc) });
      doc.font('Helvetica');
      y += 18;
    }

    if (withTableHeader) {
      y = this.drawTableHeader(doc, y, canReadAll);
    }

    doc.x = PAGE_MARGIN;
    doc.y = y;
    return y;
  }

  needsNewPage(doc, y, blockHeight = ROW_HEIGHT) {
    return y + blockHeight > this.contentBottom(doc);
  }

  drawSummaryPage(doc, summary, meta, generatedBy, generatedAt, month) {
    this.drawLogo(doc, PAGE_MARGIN, PAGE_MARGIN, 56, 56);

    doc.fontSize(18).fillColor('#1C1C1E').font('Helvetica-Bold');
    this.safeText(doc, BRAND.name, PAGE_MARGIN + 68, PAGE_MARGIN + 6, { width: 300 });
    doc.fontSize(9).fillColor('#8E8E93').font('Helvetica');
    this.safeText(doc, BRAND.tagline, PAGE_MARGIN + 68, PAGE_MARGIN + 28, { width: 300 });

    doc.fontSize(15).fillColor('#007AFF').font('Helvetica-Bold');
    this.safeText(doc, 'Expense Report', PAGE_MARGIN, PAGE_MARGIN + 72, { width: 300 });
    doc.fontSize(10).fillColor('#3C3C43').font('Helvetica');
    this.safeText(doc, `Period: ${summary.monthLabel}`, PAGE_MARGIN, PAGE_MARGIN + 94, { width: 400 });
    this.safeText(
      doc,
      `Report ID: EXP-${month.replace('-', '')}-${Date.now().toString(36).toUpperCase()}`,
      PAGE_MARGIN,
      PAGE_MARGIN + 108,
      { width: 400 },
    );
    this.safeText(doc, `Generated by: ${generatedBy}`, PAGE_MARGIN, PAGE_MARGIN + 122, { width: 400 });
    this.safeText(doc, `Generated at: ${generatedAt} (PKT)`, PAGE_MARGIN, PAGE_MARGIN + 136, { width: 400 });

    const boxY = PAGE_MARGIN + 158;
    const boxW = (this.pageWidth(doc) - 16) / 3;
    const boxes = [
      { label: 'Total spent', value: formatPkr(summary.totalAmount) },
      { label: 'Transactions', value: String(summary.expenseCount ?? 0) },
      { label: 'Daily average', value: formatPkr(summary.avgPerDay ?? 0) },
    ];

    boxes.forEach((box, i) => {
      const x = PAGE_MARGIN + i * (boxW + 8);
      doc.roundedRect(x, boxY, boxW, 46, 6).fillAndStroke('#F2F2F7', '#E5E5EA');
      doc.fontSize(7.5).fillColor('#8E8E93').font('Helvetica');
      this.safeText(doc, box.label, x + 8, boxY + 8, { width: boxW - 16 });
      doc.fontSize(12).fillColor('#1C1C1E').font('Helvetica-Bold');
      this.safeText(doc, box.value, x + 8, boxY + 22, { width: boxW - 16 });
      doc.font('Helvetica');
    });

    let y = boxY + 58;
    doc.fontSize(10).fillColor('#1C1C1E').font('Helvetica-Bold');
    this.safeText(doc, 'Spending by category', PAGE_MARGIN, y, { width: 300 });
    y += 14;
    doc.font('Helvetica').fontSize(8.5).fillColor('#3C3C43');

    (summary.byCategory ?? []).slice(0, 10).forEach((cat) => {
      if (this.needsNewPage(doc, y, 12)) return;
      this.safeText(doc, `${cat.name}: ${formatPkr(cat.amount)} (${cat.percentage}%)`, PAGE_MARGIN, y, {
        width: this.pageWidth(doc),
      });
      y += 12;
    });

    if (summary.previousMonth && !this.needsNewPage(doc, y, 14)) {
      y += 4;
      const ch = summary.previousMonth.changePercent;
      doc.fillColor(ch > 0 ? '#FF3B30' : '#34C759');
      this.safeText(
        doc,
        `vs previous month: ${ch > 0 ? '+' : ''}${ch}% (${formatPkr(summary.previousMonth.changeAmount)})`,
        PAGE_MARGIN,
        y,
        { width: this.pageWidth(doc) },
      );
      y += 14;
    }

    doc.x = PAGE_MARGIN;
    doc.y = y;
    return y;
  }

  async streamPdf(query, reqUser, roles, res) {
    const { filter, month, canReadAll } = this.buildExportFilter(query, reqUser, roles);
    const summary = await expenseService.summary({ month, userId: query.userId }, reqUser, roles);

    const generatedBy =
      reqUser.fullName ??
      (`${reqUser.firstName ?? ''} ${reqUser.lastName ?? ''}`.trim() || reqUser.email);
    const generatedAt = formatDateTime(new Date());
    const meta = { generatedBy, generatedAt, month, monthLabel: summary.monthLabel };

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="expense-report-${month}.pdf"`);
    res.setHeader('Cache-Control', 'no-store');

    const doc = new PDFDocument({
      size: 'A4',
      margin: PAGE_MARGIN,
      bufferPages: false,
      autoFirstPage: true,
      info: {
        Title: `Expense Report ${summary.monthLabel}`,
        Author: generatedBy,
        Subject: `${BRAND.name} Expense Report`,
        Creator: BRAND.name,
      },
    });

    doc.pipe(res);

    const pageNumRef = { value: 1 };

    let y = this.drawSummaryPage(doc, summary, meta, generatedBy, generatedAt, month);

    const tableIntroHeight = 36 + TABLE_HEADER_HEIGHT;
    if (this.needsNewPage(doc, y, tableIntroHeight + ROW_HEIGHT * 2)) {
      y = this.startNewPage(doc, meta, pageNumRef);
    } else {
      y += 16;
    }

    doc.fontSize(11).fillColor('#1C1C1E').font('Helvetica-Bold');
    this.safeText(doc, 'Transaction details', PAGE_MARGIN, y, { width: this.pageWidth(doc) });
    doc.font('Helvetica').fontSize(8).fillColor('#8E8E93');
    this.safeText(doc, `All expenses for ${summary.monthLabel}`, PAGE_MARGIN, y + 14, {
      width: this.pageWidth(doc),
    });
    y += 30;
    y = this.drawTableHeader(doc, y, canReadAll);

    let rowIndex = 0;
    let runningTotal = 0;

    const cursor = expenseRepository.model
      .find(filter)
      .populate([
        { path: 'categoryId', select: 'name slug' },
        { path: 'userId', select: 'firstName lastName email' },
      ])
      .sort({ date: -1, _id: 1 })
      .lean()
      .cursor({ batchSize: BATCH_SIZE });

    for await (const expense of cursor) {
      if (this.needsNewPage(doc, y, ROW_HEIGHT)) {
        y = this.startNewPage(doc, meta, pageNumRef, { withTableHeader: true, canReadAll });
      }

      runningTotal += expense.amount ?? 0;
      y = this.drawTableRow(doc, expense, y, rowIndex, canReadAll);
      rowIndex += 1;

      if (rowIndex % BATCH_SIZE === 0) {
        await new Promise((resolve) => setImmediate(resolve));
      }
    }

    if (rowIndex === 0) {
      if (this.needsNewPage(doc, y, 20)) {
        y = this.startNewPage(doc, meta, pageNumRef, { withTableHeader: true, canReadAll });
      }
      doc.fontSize(9).fillColor('#8E8E93').font('Helvetica');
      this.safeText(doc, 'No transactions for this period.', PAGE_MARGIN, y + 4, {
        width: this.pageWidth(doc),
      });
      y += 20;
    }

    const totalBlockHeight = 24;
    if (this.needsNewPage(doc, y, totalBlockHeight)) {
      y = this.startNewPage(doc, meta, pageNumRef);
    }

    y += 6;
    doc
      .moveTo(PAGE_MARGIN, y)
      .lineTo(doc.page.width - PAGE_MARGIN, y)
      .strokeColor('#C6C6C8')
      .lineWidth(0.5)
      .stroke();
    y += 8;

    doc.fontSize(9.5).fillColor('#1C1C1E').font('Helvetica-Bold');
    this.safeText(
      doc,
      `Grand total (${rowIndex} transactions): ${formatPkr(runningTotal)}`,
      PAGE_MARGIN,
      y,
      { width: this.pageWidth(doc), align: 'right' },
    );

    this.drawPageFooter(doc, meta, pageNumRef.value);
    doc.end();
  }
}

export default new ExpenseReportService();
