export const PDF_LABELS = {
  en: {
    title: 'Patient Admission Record',
    registrationNo: 'Registration No.',
    admissionNo: 'Admission No.',
    patientId: 'Patient ID',
    admissionDate: 'Admission Date',
    status: 'Status',
    generatedAt: 'Generated',
    basicInfo: 'Basic Information',
    fullName: 'Full Name',
    gender: 'Gender',
    dob: 'Date of Birth',
    age: 'Age',
    maritalStatus: 'Marital Status',
    nationality: 'Nationality',
    religion: 'Religion',
    cnic: 'CNIC',
    passport: 'Passport',
    phone: 'Phone',
    alternatePhone: 'Alt. Phone',
    email: 'Email',
    education: 'Education',
    monthlyIncome: 'Monthly Income',
    address: 'Current Address',
    permanentAddress: 'Permanent Address',
    city: 'City',
    province: 'Province',
    country: 'Country',
    postalCode: 'Postal Code',
    occupation: 'Occupation',
    guardian: 'Guardian Information',
    guardianName: 'Guardian Name',
    relationship: 'Relationship',
    guardianPhone: 'Guardian Phone',
    guardianEmail: 'Guardian Email',
    guardianAddress: 'Guardian Address',
    emergency: 'Emergency Contacts',
    contactName: 'Contact',
    admission: 'Admission Details',
    admissionType: 'Admission Type',
    referredBy: 'Referred By',
    hospitalName: 'Hospital',
    doctor: 'Attending Doctor',
    reason: 'Reason for Admission',
    complaint: 'Chief Complaint',
    symptoms: 'Presenting Symptoms',
    admissionNotes: 'Admission Notes',
    medical: 'Medical History',
    allergies: 'Allergies',
    bloodGroup: 'Blood Group',
    height: 'Height',
    weight: 'Weight',
    bmi: 'BMI',
    conditions: 'Existing Conditions',
    medications: 'Current Medications',
    surgeries: 'Past Surgeries',
    hospitalizations: 'Prior Hospitalizations',
    disability: 'Disability',
    infectiousDisease: 'Infectious Disease',
    medicalNotes: 'Medical Notes',
    substance: 'Substance Use History',
    substanceItem: 'Substance',
    mental: 'Mental Health',
    depression: 'Depression',
    anxiety: 'Anxiety',
    aggression: 'Aggression',
    suicidalHistory: 'Suicidal History',
    hallucinations: 'Hallucinations',
    selfHarm: 'Self-harm History',
    psychiatricTreatment: 'Psychiatric Treatment',
    psychiatricNotes: 'Psychiatric Notes',
    social: 'Social Information',
    employmentStatus: 'Employment',
    educationLevel: 'Education Level',
    familySupport: 'Family Support',
    livingSituation: 'Living Situation',
    financialCondition: 'Financial Condition',
    criminalHistory: 'Criminal History',
    legalCases: 'Legal Cases',
    socialNotes: 'Social Notes',
    documents: 'Uploaded Documents',
    documentType: 'Document',
    timeline: 'Patient Timeline & Record History',
    timelineDate: 'Date & Time',
    timelineEvent: 'Event',
    timelineDetail: 'Details',
    consent: 'Consent & Agreements',
    patientConsent: 'Patient Consent',
    guardianConsent: 'Guardian Consent',
    treatmentAgreement: 'Treatment Agreement',
    hospitalRules: 'Hospital Rules',
    privacyAgreement: 'Privacy Agreement',
    emergencyTreatment: 'Emergency Treatment',
    dataProcessing: 'Data Processing',
    signatures: 'Signatures',
    patientSig: 'Patient Signature',
    guardianSig: 'Guardian Signature',
    officerSig: 'Admitting Officer',
    date: 'Date',
    yes: 'Yes',
    no: 'No',
    footer: 'Confidential medical record',
    noPhoto: 'No photo',
    qrLabel: 'Scan ID',
    discharge: 'Discharge Information',
    dischargeDate: 'Discharge Date',
    dischargeReason: 'Discharge Reason',
    followUpDate: 'Follow-up Date',
    followUpInstructions: 'Follow-up Instructions',
    doctorRemarks: 'Doctor Remarks',
    patientIdentification: 'Patient Identification',
    softwareBy: 'Software by',
  },
};

export const TIMELINE_LABELS = {
  en: {
    patient_created: 'Patient record created',
    admission_updated: 'Admission details updated',
    medical_updated: 'Medical information updated',
    guardian_updated: 'Guardian information updated',
    document_uploaded: 'Document uploaded',
    consent_signed: 'Consent signed',
    status_changed: 'Status changed',
    discharged: 'Patient discharged',
    pdf_generated: 'Admission PDF generated',
    patient_updated: 'Patient record updated',
  },
};

export const DOCUMENT_TYPE_LABELS = {
  en: {
    patient_photo: 'Patient photo',
    cnic_front: 'CNIC (front)',
    cnic_back: 'CNIC (back)',
    guardian_cnic: 'Guardian CNIC',
    medical_report: 'Medical report',
    lab_report: 'Lab report',
    prescription: 'Prescription',
    referral_letter: 'Referral letter',
    police_clearance: 'Police clearance',
    consent_form: 'Consent form',
    other: 'Other',
  },
};

export const t = (_lang, key) => PDF_LABELS.en[key] ?? key;

export const timelineLabel = (_lang, event) =>
  TIMELINE_LABELS.en[event] ?? TIMELINE_LABELS.en.patient_updated ?? event;

export const docTypeLabel = (_lang, type) => DOCUMENT_TYPE_LABELS.en[type] ?? type;
