import { ROLES } from '../constants/roles.js';
import { PERMISSIONS, PERMISSION_VALUES } from '../constants/permissions.js';

/**
 * Role -> permission mapping. Super admin implicitly holds every permission.
 * Keep this the single source of authority; middleware reads from it.
 */
const P = PERMISSIONS;

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: PERMISSION_VALUES,
  [ROLES.ADMIN]: [
    P.USER_CREATE, P.USER_READ, P.USER_UPDATE, P.USER_DELETE, P.USER_MANAGE_ROLES,
    P.ROLE_CREATE, P.ROLE_READ, P.ROLE_UPDATE, P.ROLE_DELETE,
    P.CATEGORY_CREATE, P.CATEGORY_READ, P.CATEGORY_UPDATE, P.CATEGORY_DELETE,
    P.EXPENSE_CREATE, P.EXPENSE_READ, P.EXPENSE_UPDATE, P.EXPENSE_DELETE, P.EXPENSE_READ_ALL,
    P.ATTENDANCE_READ, P.ATTENDANCE_READ_ALL, P.ATTENDANCE_CREATE, P.ATTENDANCE_UPDATE, P.ATTENDANCE_DELETE,
    P.OFFICE_SETTINGS_READ,
    P.PATIENT_READ, P.PATIENT_CREATE, P.PATIENT_UPDATE, P.PATIENT_DELETE,
    P.PATIENT_PDF_DOWNLOAD, P.PATIENT_PDF_PRINT, P.PATIENT_DOCUMENT_MANAGE,
    P.AUDIT_READ, P.SETTINGS_READ, P.SETTINGS_UPDATE,
  ],
  [ROLES.MANAGER]: [
    P.USER_READ, P.USER_UPDATE, P.SETTINGS_READ,
    P.CATEGORY_READ,
    P.EXPENSE_CREATE, P.EXPENSE_READ, P.EXPENSE_UPDATE, P.EXPENSE_DELETE, P.EXPENSE_READ_ALL,
    P.ATTENDANCE_READ, P.ATTENDANCE_READ_ALL, P.ATTENDANCE_CREATE, P.ATTENDANCE_UPDATE,
    P.OFFICE_SETTINGS_READ,
    P.PATIENT_READ, P.PATIENT_CREATE, P.PATIENT_UPDATE,
    P.PATIENT_PDF_DOWNLOAD, P.PATIENT_DOCUMENT_MANAGE,
  ],
  [ROLES.USER]: [
    P.USER_READ,
    P.CATEGORY_READ,
    P.EXPENSE_CREATE, P.EXPENSE_READ, P.EXPENSE_UPDATE, P.EXPENSE_DELETE,
    P.ATTENDANCE_READ, P.ATTENDANCE_CHECKIN,
    P.OFFICE_SETTINGS_READ,
  ],
});

export const getPermissionsForRoles = (roles = []) => {
  const set = new Set();
  roles.forEach((role) => (ROLE_PERMISSIONS[role] || []).forEach((p) => set.add(p)));
  return [...set];
};

export const roleHasPermission = (roles = [], permission) =>
  getPermissionsForRoles(roles).includes(permission);
